import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppContextProvider } from "../components/_providers/app-provider";
import "./globals.css";
import { AuthServiceContextProvider } from "@/services/auth-service/auth-service-LEGACY";
import { ClientSessionProvider } from "@/context/client-session-provider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className="dark">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
      />
      <body className={`${inter.className} bg-slate-900`}>
        {/* <AuthServiceContextProvider> */}
        <ClientSessionProvider session={session}>
          <AppContextProvider>{children}</AppContextProvider>
        </ClientSessionProvider>
        {/* </AuthServiceContextProvider> */}
      </body>
    </html>
  );
}
