import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppContextProvider } from "../components/_providers/app-provider";
import "./global-styles.css";
import { AuthServiceContextProvider } from "@/services/auth-service/auth.service";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-bs-theme="dark">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
      />
      <body className={inter.className}>
        <AuthServiceContextProvider>
          <AppContextProvider>{children}</AppContextProvider>
        </AuthServiceContextProvider>
      </body>
    </html>
  );
}
